// Dutch game names for the overview; generated from lib/games/*/*_module.dart.
export const names = {
  "backgammon": "Backgammon",
  "bedrieger": "Wie is de bedrieger?",
  "blokpuzzel": "Blokpuzzel",
  "bluf": "Bluf",
  "boerenbridge": "Boerenbridge",
  "boterkaas": "Boter, kaas en eieren",
  "buizen": "Buizen verbinden",
  "cijferstenen": "Cijferstenen",
  "dammen": "Dammen",
  "ergerjeniet": "Pionnenrace",
  "evenwicht": "Evenwicht",
  "groepjes": "Groepjes",
  "hartenjagen": "Hartenjagen",
  "kaasmarkt": "Kaasmarkt",
  "keezen": "Keezen",
  "klaverjassen": "Klaverjassen",
  "kroontjes": "Kroontjes",
  "kruisjes": "Kruisjes",
  "mexen": "Mexen",
  "mijnenveger": "Mijnenveger",
  "nonogram": "Nonogram",
  "omdraaien": "Omdraaien",
  "pesten": "Pesten",
  "raadhet": "Raad het",
  "reversi": "Reversi",
  "schaken": "Schaken",
  "schuiven": "Schuiven",
  "solitaire": "Solitaire",
  "sudoku": "Sudoku",
  "tegelberg": "Tegelberg",
  "toepen": "Toepen",
  "vieropeenrij": "Vier op een rij",
  "vragen": "Zou je liever…",
  "watersorteren": "Water sorteren",
  "weerwolven": "Weerwolven",
  "woordje": "Woordje",
  "woordzoeker": "Woordzoeker",
  "yacht": "Yacht",
  "zandloper": "Zandloper",
  "zeeslag": "Zeeslag",
  "zevenklap": "Zevenklap"
};
